# Generated by Django 3.2.7 on 2021-10-05 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elsys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='HP',
        ),
        migrations.RemoveField(
            model_name='car',
            name='yearProduction',
        ),
    ]
