# Generated by Django 3.2.7 on 2021-10-05 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsys', '0002_auto_20211005_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='HP',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='car',
            name='yearProduction',
            field=models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
