# Generated by Django 3.2.7 on 2021-10-19 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elsys', '0003_auto_20211005_0808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='HP',
            new_name='hp',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='yearProduction',
            new_name='year_production',
        ),
    ]
